### ISSUE TITLE
mysqldump 8 crashes migration

### ISSUE THREAD

**Issue by thomasg87** [javalon/anonymizer-mysql#1]
If mysqldump in version 8 is used, it crashes the migration which leads to further errors.

This is related to this issue:
https://stackoverflow.com/questions/51614140/how-to-disable-column-statistics-in-mysql-8-permanently

**Comment by thomasg87** [comment]
This patch allows anonymizer-mysql to work with mysqldump 8

[add-column-statistics.diff.zip](https://github.com/javalon/anonymizer-mysql/files/3116631/add-column-statistics.diff.zip)

**Comment by javalon** [comment]
Thanks, @yummydummy

I updated the version  (e40300a512622b91852011bedea4ec6a0c01889e) with a new command '-8' to add the option to 'mysqldump' and disable column statistics for MySQL 8.x

**Comment by thomasg87** [comment]
perfect! Thanks!
