### ISSUE TITLE
Doesnt work for SQL accounts that have no password.

### ISSUE THREAD

**Issue by KieranDevvs** [javalon/anonymizer-mysql#2]
When running against a user without a password i.e username: `root` & password: `<blank>` the credentials are never passed into mysql or mysqldump.

![image](https://user-images.githubusercontent.com/21192520/154735001-de48adcb-eb5a-48d3-b325-04967853051d.png)

**Comment by javalon** [comment]
Hi @KieranDevvs,

Thank you for communicating to me this case.

I take note of it and will try to improve the project in the coming weeks.

Regards.

**Comment by KieranDevvs** [comment]
@javalon Im going to close this as I no longer have interest.
